blank_issues_enabled: false
contact_links:
  - name: apexcharts-card Community Support
    url: https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877
    about: Please ask and answer questions here.
